// <auto-generated />
namespace TelefonRehberi.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v35 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v35));
        
        string IMigrationMetadata.Id
        {
            get { return "202002012220142_v3.5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
